name-template: v${{MAJOR}}.${{MINOR}}.${{PATCH}}
tag-template: v${{MAJOR}}.${{MINOR}}.${{PATCH}}
template: |
               ## Changes
               
               $CHANGES
               
               ## Contributors
               
               $CONTRIBUTORS
               
               ## Commits
               
               $COMMITS