name: CI/CD Workflow

on:
  pull_request:
    branches:
      - '*'

  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  lint-and-test:
    name: Lint et test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Installation de node 20
        uses: actions/setup-node@v4
        with:
         node-version: 20

      - name: node test
        run: node -v

      - name: npm test
        run: npm -v
