name: CI/CD Workflow

on:
  pull_request:
    branches:
      - '*'

  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  lint-and-test:
    name: Lint et test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Installation de node 20
        uses: actions/setup-node@v4
        with:
         node-version: 20

      - name: Installation des dépendances javascript
        run: npm install

      - name: Lint du fchier index.js
        run: npm run lint-index

      - name: Lint du fchier test.js
        run: npm run lint-test

      - name: Lint du fchier Dockerfile
        run: hadolint Dockerfile
